### ISSUE TITLE
setup.py - install_requires - new dependencies

### ISSUE THREAD

**Issue by lexruee** [lexruee/xwot.py#22]
The property install_requires in the setup.py file shuld be updated in order to include
the new dependencies:
 * autobahn
 * websockets

**Comment by aruppen** [comment]
I think that autobahn is sufficient. I'll add it in my fork. Since I have some more changes in the publisher which I'll pull-request soon.

**Comment by aruppen** [comment]
Closed in 2cc028aef4169554d6086d43d46c4e8d5be3426d
